// File generated by FlutterFire CLI / manual config for cashflowIQ
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVEA43L_AfXDP753b5I9pl7azfAJRFC8M',
    appId: '1:124553852455:android:8f5fb34ea794dd6f68c002',
    messagingSenderId: '124553852455',
    projectId: 'cashflowiq-6ac48',
    storageBucket: 'cashflowiq-6ac48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQVDcYyOJ3BKjIhShJAiPUl90O3Z7zRzs',
    appId: '1:124553852455:ios:6665d597c9fba48d68c002',
    messagingSenderId: '124553852455',
    projectId: 'cashflowiq-6ac48',
    storageBucket: 'cashflowiq-6ac48.firebasestorage.app',
    iosBundleId: 'com.cashflowIQ.app',
  );
}
